URL= https://www.saucedemo.com/
UserName = //input[@name="user-name"]
Password = //input[@name="password"]
Submit = //input[@type="submit"]
Menu = //button[@id="react-burger-menu-btn"]
CrossBtn = //button[@id="react-burger-cross-btn"]